import 'dart:async';
import 'dart:io' show Platform;

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../features/auth/presentation/providers/auth_providers.dart';
import '../../firebase_options.dart';

/// Lets push messages that arrive while the app is open show a snackbar
/// from anywhere.
final rootScaffoldMessengerKey = GlobalKey<ScaffoldMessengerState>();

/// Firebase setup (config generated by `flutterfire configure`). If it fails,
/// the app runs normally with push turned off.
class PushNotifications {
  PushNotifications._();

  static bool _available = false;
  static bool get available => _available;

  static Future<void> initialize() async {
    if (kIsWeb) return;
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      _available = true;
    } catch (error) {
      debugPrint('Push notifications disabled: $error');
    }
  }

  /// Screen to open for a push. Custom notifications have no screen of their
  /// own, so they open the notification list for the user's role.
  static String routeFor(RemoteMessage message, {required bool instructor}) {
    final route = message.data['route'];
    if (route is String && route.startsWith('/')) return route;
    return instructor ? '/instructor/notifications' : '/notifications';
  }

  /// Whether the same message also arrives in-app over the socket, which
  /// already shows a banner while the app is open.
  static bool hasInAppCopy(RemoteMessage message) =>
      message.data['inApp'] == '1';
}

/// Registers this device's FCM token with the backend while a user is
/// signed in, and keeps it up to date when Firebase rotates it.
final pushRegistrationProvider = NotifierProvider<PushRegistration, void>(
  PushRegistration.new,
);

class PushRegistration extends Notifier<void> {
  String? _token;
  StreamSubscription<String>? _refreshSubscription;

  @override
  void build() {
    // Re-run only when the signed-in user changes.
    final userId = ref.watch(
      authControllerProvider.select((auth) => auth.asData?.value?.id),
    );
    ref.onDispose(() => _refreshSubscription?.cancel());
    if (userId == null || !PushNotifications.available) return;
    Future.microtask(_register);
  }

  Future<void> _register() async {
    try {
      final messaging = FirebaseMessaging.instance;
      final settings = await messaging.requestPermission();
      if (settings.authorizationStatus == AuthorizationStatus.denied) return;

      // iOS needs the APNs token before an FCM token can be issued.
      if (Platform.isIOS && !await _waitForApnsToken(messaging)) return;

      final token = await messaging.getToken();
      if (token == null || !ref.mounted) return;
      await _send(token);

      await _refreshSubscription?.cancel();
      _refreshSubscription = messaging.onTokenRefresh.listen(_send);
    } catch (error) {
      debugPrint('Push registration failed: $error');
    }
  }

  Future<bool> _waitForApnsToken(FirebaseMessaging messaging) async {
    for (var attempt = 0; attempt < 5; attempt++) {
      if (await messaging.getAPNSToken() != null) return true;
      await Future<void>.delayed(const Duration(seconds: 1));
    }
    return false;
  }

  Future<void> _send(String token) async {
    _token = token;
    await ref.read(apiClientProvider).dio.post<void>(
      '/notifications/push-tokens',
      data: {
        'token': token,
        'platform': Platform.isIOS ? 'ios' : 'android',
        'locale': Platform.localeName,
      },
    );
  }

  /// Stops pushes to this device. Call before logging out, while the
  /// session is still valid.
  Future<void> unregister() async {
    final token = _token;
    if (token == null) return;
    _token = null;
    await _refreshSubscription?.cancel();
    _refreshSubscription = null;
    try {
      await ref
          .read(apiClientProvider)
          .dio
          .delete<void>('/notifications/push-tokens/${Uri.encodeComponent(token)}');
    } catch (_) {
      // Best effort: the server also drops tokens that move to another user.
    }
  }
}
